package net.sen.lostworlds.datagen.tag;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.sen.lostworlds.LostWorldsConstants;
import net.sen.lostworlds.block.ModBlocks;
import net.sen.lostworlds.item.ModItems;
import net.sen.lostworlds.util.ModTags;

import javax.annotation.Nullable;
import java.util.concurrent.CompletableFuture;

public class ModCreativeTabsTagProvider extends ItemTagsProvider {
    public ModCreativeTabsTagProvider(PackOutput pOutput, CompletableFuture<HolderLookup.Provider> pLookupProvider, CompletableFuture<TagLookup<Block>> pBlockTags, @Nullable ExistingFileHelper existingFileHelper) {
        super(pOutput, pLookupProvider, pBlockTags, LostWorldsConstants.MODID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        this.tag(ModTags.CreativeTabs.GENERAL).add(
                ModItems.LOST_WORLDS_BOOK.get(),
                ModItems.DICE.get(),
                ModItems.BASIC_PORTAL_CORE.get(),
                ModItems.BASIC_PORTAL_ACTIVATOR.get(),
                ModItems.OLIVE.get(),

                Item.byBlock(ModBlocks.ZINC_BLOCK.get()),
                Item.byBlock(ModBlocks.RAW_ZINC_BLOCK.get()),
                Item.byBlock(ModBlocks.ZINC_ORE.get()),
                Item.byBlock(ModBlocks.DEEPSLATE_ZINC_ORE.get()),
                ModItems.ZINC_INGOT.get(),
                ModItems.RAW_ZINC.get(),
                ModItems.ZINC_NUGGET.get(),
                ModItems.ZINC_SWORD.get(),
                ModItems.ZINC_PICKAXE.get(),
                ModItems.ZINC_SHOVEL.get(),
                ModItems.ZINC_AXE.get(),
                ModItems.ZINC_HOE.get(),
                ModItems.ZINC_HELMET.get(),
                ModItems.ZINC_CHESTPLATE.get(),
                ModItems.ZINC_LEGGINGS.get(),
                ModItems.ZINC_BOOTS.get(),
                ModItems.ZINC_HORSE_ARMOR.get(),

                Item.byBlock(ModBlocks.TIN_BLOCK.get()),
                Item.byBlock(ModBlocks.RAW_TIN_BLOCK.get()),
                Item.byBlock(ModBlocks.TIN_ORE.get()),
                Item.byBlock(ModBlocks.DEEPSLATE_TIN_ORE.get()),
                ModItems.TIN_INGOT.get(),
                ModItems.RAW_TIN.get(),
                ModItems.TIN_NUGGET.get(),
                ModItems.TIN_SWORD.get(),
                ModItems.TIN_PICKAXE.get(),
                ModItems.TIN_SHOVEL.get(),
                ModItems.TIN_AXE.get(),
                ModItems.TIN_HOE.get(),
                ModItems.TIN_HELMET.get(),
                ModItems.TIN_CHESTPLATE.get(),
                ModItems.TIN_LEGGINGS.get(),
                ModItems.TIN_BOOTS.get(),
                ModItems.TIN_HORSE_ARMOR.get(),

                Item.byBlock(ModBlocks.AURICHALCITE_BLOCK.get()),
                ModItems.AURICHALCITE.get(),

                Item.byBlock(ModBlocks.BRASS_BLOCK.get()),
                ModItems.BRASS_INGOT.get(),
                ModItems.BRASS_NUGGET.get(),
                ModItems.BRASS_SWORD.get(),
                ModItems.BRASS_PICKAXE.get(),
                ModItems.BRASS_SHOVEL.get(),
                ModItems.BRASS_AXE.get(),
                ModItems.BRASS_HOE.get(),
                ModItems.BRASS_HELMET.get(),
                ModItems.BRASS_CHESTPLATE.get(),
                ModItems.BRASS_LEGGINGS.get(),
                ModItems.BRASS_BOOTS.get(),
                ModItems.BRASS_HORSE_ARMOR.get(),

                Item.byBlock(ModBlocks.BRONZE_BLOCK.get()),
                ModItems.BRONZE_INGOT.get(),
                ModItems.BRONZE_NUGGET.get(),
                ModItems.BRONZE_SWORD.get(),
                ModItems.BRONZE_PICKAXE.get(),
                ModItems.BRONZE_SHOVEL.get(),
                ModItems.BRONZE_AXE.get(),
                ModItems.BRONZE_HOE.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.BRONZE_HORSE_ARMOR.get(),

                ModItems.DATA_TABLET.get(),
                ModItems.MEDUSA_HEAD.get(),

                ModItems.MAGICAL_DOWSING_ROD.get(),
                ModItems.BAR_BRAWL_RECORD.get(),
                Item.byBlock(ModBlocks.SOUND_BLOCK.get()),
                Item.byBlock(ModBlocks.ALLOY_SMELTER.get()),

                ModItems.CUSTOM_BOW.get(),
                ModItems.ALEXANDRITE_SHIELD.get(),

                ModItems.STYX_WATER_BUCKET.get(),

                Item.byBlock(ModBlocks.ELDER_WOOD_LOG.get()),
                Item.byBlock(ModBlocks.STRIPPED_ELDER_WOOD_LOG.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD.get()),
                Item.byBlock(ModBlocks.STRIPPED_ELDER_WOOD.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_LEAVES.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_SAPLING.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_SLAB.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_STAIRS.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_DOOR.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_TRAPDOOR.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_FENCE.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_FENCE_GATE.get()),
                Item.byBlock(ModBlocks.ELDER_WOOD_PLANKS_BUTTON.get()),
                ModItems.ELDER_WOOD_SIGN.get(),
                ModItems.ELDER_WOOD_HANGING_SIGN.get(),

                Item.byBlock(ModBlocks.OLIVE_LOG.get()),
                Item.byBlock(ModBlocks.STRIPPED_OLIVE_LOG.get()),
                Item.byBlock(ModBlocks.OLIVE_WOOD.get()),
                Item.byBlock(ModBlocks.STRIPPED_OLIVE_WOOD.get()),
                Item.byBlock(ModBlocks.OLIVE_LEAVES.get()),
                Item.byBlock(ModBlocks.OLIVE_SAPLING.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_SLAB.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_STAIRS.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_DOOR.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_TRAPDOOR.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_FENCE.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_FENCE_GATE.get()),
                Item.byBlock(ModBlocks.OLIVE_PLANKS_BUTTON.get()),
                ModItems.OLIVE_SIGN.get(),
                ModItems.OLIVE_HANGING_SIGN.get(),

                Item.byBlock(ModBlocks.MYRRH_LOG.get()),
                Item.byBlock(ModBlocks.STRIPPED_MYRRH_LOG.get()),
                Item.byBlock(ModBlocks.MYRRH_WOOD.get()),
                Item.byBlock(ModBlocks.STRIPPED_MYRRH_WOOD.get()),
                Item.byBlock(ModBlocks.MYRRH_LEAVES.get()),
                Item.byBlock(ModBlocks.MYRRH_SAPLING.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_SLAB.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_STAIRS.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_DOOR.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_TRAPDOOR.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_FENCE.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_FENCE_GATE.get()),
                Item.byBlock(ModBlocks.MYRRH_PLANKS_BUTTON.get()),
                ModItems.MYRRH_SIGN.get(),
                ModItems.MYRRH_HANGING_SIGN.get(),

                Item.byBlock(ModBlocks.LAUREL_LOG.get()),
                Item.byBlock(ModBlocks.STRIPPED_LAUREL_LOG.get()),
                Item.byBlock(ModBlocks.LAUREL_WOOD.get()),
                Item.byBlock(ModBlocks.STRIPPED_LAUREL_WOOD.get()),
                Item.byBlock(ModBlocks.LAUREL_LEAVES.get()),
                Item.byBlock(ModBlocks.LAUREL_SAPLING.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_SLAB.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_STAIRS.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_DOOR.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_TRAPDOOR.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_FENCE.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_FENCE_GATE.get()),
                Item.byBlock(ModBlocks.LAUREL_PLANKS_BUTTON.get()),
                ModItems.LAUREL_SIGN.get(),
                ModItems.LAUREL_HANGING_SIGN.get(),

                Item.byBlock(ModBlocks.CYPRESS_LOG.get()),
                Item.byBlock(ModBlocks.STRIPPED_CYPRESS_LOG.get()),
                Item.byBlock(ModBlocks.CYPRESS_WOOD.get()),
                Item.byBlock(ModBlocks.STRIPPED_CYPRESS_WOOD.get()),
                Item.byBlock(ModBlocks.CYPRESS_LEAVES.get()),
                Item.byBlock(ModBlocks.CYPRESS_SAPLING.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_SLAB.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_STAIRS.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_DOOR.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_TRAPDOOR.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_FENCE.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_FENCE_GATE.get()),
                Item.byBlock(ModBlocks.CYPRESS_PLANKS_BUTTON.get()),
                ModItems.CYPRESS_SIGN.get(),
                ModItems.CYPRESS_HANGING_SIGN.get()
        );

        this.tag(ModTags.CreativeTabs.SPAWN_EGGS).add(
                ModItems.RHINO_SPAWN_EGG.get(),
                ModItems.DWARVES_SPAWN_EGG.get(),
                ModItems.ELVES_SPAWN_EGG.get(),
                ModItems.SHARK_SPAWN_EGG.get(),
                ModItems.MORAY_EELS_SPAWN_EGG.get(),
                ModItems.ELECTRIC_EELS_SPAWN_EGG.get(),
                ModItems.JELLYFISH_SPAWN_EGG.get(),
                ModItems.GIANT_SQUID_SPAWN_EGG.get(),
                ModItems.RAY_SPAWN_EGG.get(),
                ModItems.GIANT_OCTOPUS_SPAWN_EGG.get(),
                ModItems.NUDIBRANCH_SLUG_SPAWN_EGG.get(),
                ModItems.GREAT_WHITE_SPAWN_EGG.get(),
                ModItems.ANGLER_FISH_SPAWN_EGG.get(),
                ModItems.SEAHORSE_SPAWN_EGG.get(),
                ModItems.CLOWNFISH_SPAWN_EGG.get(),
                ModItems.ATLANTIAN_GURDIAN_SPAWN_EGG.get(),
                ModItems.SIREN_SPAWN_EGG.get(),
                ModItems.MERFOLK_SPAWN_EGG.get(),
                ModItems.ATLANTIAN_SPAWN_EGG.get(),
                ModItems.TANG_FISH_SPAWN_EGG.get(),
                ModItems.TUNA_SPAWN_EGG.get()
        );

        this.tag(ModTags.CreativeTabs.UNDERWORLD).add(
                Item.byBlock(ModBlocks.UNDERWORLD_PORTAL_FRAME.get()),

//                Item.byBlock(ModBlocks.UNDERWORLD_GRASS_BLOCK.get()),

                Item.byBlock(ModBlocks.TARTARUS_STONE.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_STAIRS.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_SLAB.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BUTTON.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_WALL.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_SMOOTH_STONE.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_COBBLESTONE.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_COBBLESTONE_STAIRS.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_COBBLESTONE_SLAB.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_COBBLESTONE_WALL.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_COBBLESTONE_MOSSY.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BRICKS.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BRICKS_STAIRS.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BRICKS_SLAB.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BRICKS_WALL.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BRICKS_MOSSY.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BRICKS_CRACKED.get()),
                Item.byBlock(ModBlocks.TARTARUS_STONE_BRICKS_CHISELED.get()),

                Item.byBlock(ModBlocks.UNDERWORLD_DIRT.get()),

                Item.byBlock(ModBlocks.ORICHALCUM_BLOCK.get()),
                Item.byBlock(ModBlocks.RAW_ORICHALCUM_BLOCK.get()),
                Item.byBlock(ModBlocks.ORICHALCUM_ORE.get()),
                Item.byBlock(ModBlocks.DEEPSLATE_ORICHALCUM_ORE.get()),
                ModItems.ORICHALCUM_INGOT.get(),
                ModItems.RAW_ORICHALCUM.get(),
                ModItems.ORICHALCUM_NUGGET.get(),
                ModItems.ORICHALCUM_SWORD.get(),
                ModItems.ORICHALCUM_PICKAXE.get(),
                ModItems.ORICHALCUM_SHOVEL.get(),
                ModItems.ORICHALCUM_AXE.get(),
                ModItems.ORICHALCUM_HOE.get(),
                ModItems.ORICHALCUM_HELMET.get(),
                ModItems.ORICHALCUM_CHESTPLATE.get(),
                ModItems.ORICHALCUM_LEGGINGS.get(),
                ModItems.ORICHALCUM_BOOTS.get(),
                ModItems.ORICHALCUM_HORSE_ARMOR.get(),

                Item.byBlock(ModBlocks.ADAMANT_BLOCK.get()),
                Item.byBlock(ModBlocks.ADAMANT_ORE.get()),
                Item.byBlock(ModBlocks.DEEPSLATE_ADAMANT_ORE.get()),
                ModItems.ADAMANT.get(),

                ModItems.POMEGRANATE.get(),
                ModItems.POMEGRANATE_SEEDS.get(),

                Item.byBlock(ModBlocks.IRIS_FLOWER.get())
        );

        this.tag(ModTags.CreativeTabs.NIDAVELLIR).add(
                Item.byBlock(ModBlocks.NIDAVELLIR_PORTAL_FRAME.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BUTTON.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_SMOOTH_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_COBBLESTONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_COBBLESTONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_COBBLESTONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_COBBLESTONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_COBBLESTONE_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BRICKS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BRICKS_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BRICKS_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BRICKS_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BRICKS_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BRICKS_CRACKED.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_BRICKS_CHISELED.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_IRON_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_GOLD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_COPPER_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_TIN_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_ZINC_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_DIAMOND_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_EMERALD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_COAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_REDSTONE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_LAPIS_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_AQUAMARINE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_OPAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_RUBY_ORE.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_IRON_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_GOLD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_COPPER_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_TIN_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_ZINC_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_DIAMOND_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_EMERALD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_COAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_REDSTONE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_LAPIS_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_AQUAMARINE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_OPAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_SOFT_STONE_RUBY_ORE_CLUSTER.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BUTTON.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_SMOOTH_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_COBBLESTONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_COBBLESTONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_COBBLESTONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_COBBLESTONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_COBBLESTONE_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BRICKS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BRICKS_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BRICKS_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BRICKS_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BRICKS_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BRICKS_CRACKED.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_BRICKS_CHISELED.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_IRON_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_GOLD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_COPPER_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_TIN_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_ZINC_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_DIAMOND_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_EMERALD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_COAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_REDSTONE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_LAPIS_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_AQUAMARINE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_OPAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_RUBY_ORE.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_IRON_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_GOLD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_COPPER_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_TIN_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_ZINC_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_DIAMOND_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_EMERALD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_COAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_REDSTONE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_LAPIS_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_AQUAMARINE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_HARD_STONE_RUBY_ORE_CLUSTER.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BUTTON.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_SMOOTH_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_COBBLESTONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_COBBLESTONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_COBBLESTONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_COBBLESTONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_COBBLESTONE_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BRICKS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BRICKS_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BRICKS_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BRICKS_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BRICKS_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BRICKS_CRACKED.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_BRICKS_CHISELED.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_IRON_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_GOLD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_COPPER_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_TIN_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_ZINC_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_DIAMOND_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_EMERALD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_COAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_REDSTONE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_LAPIS_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_AQUAMARINE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_OPAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_RUBY_ORE.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_IRON_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_GOLD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_COPPER_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_TIN_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_ZINC_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_DIAMOND_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_EMERALD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_COAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_REDSTONE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_LAPIS_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_AQUAMARINE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_OPAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_ENHANCED_STONE_RUBY_ORE_CLUSTER.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BUTTON.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_SMOOTH_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_COBBLESTONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_COBBLESTONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_COBBLESTONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_COBBLESTONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_COBBLESTONE_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BRICKS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BRICKS_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BRICKS_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BRICKS_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BRICKS_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BRICKS_CRACKED.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_BRICKS_CHISELED.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_IRON_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_GOLD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_COPPER_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_TIN_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_ZINC_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_DIAMOND_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_EMERALD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_COAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_REDSTONE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_LAPIS_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_AQUAMARINE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_OPAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_RUBY_ORE.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_IRON_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_GOLD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_COPPER_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_TIN_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_ZINC_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_DIAMOND_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_EMERALD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_COAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_REDSTONE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_LAPIS_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_AQUAMARINE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_OPAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_DEEPSLATE_STONE_RUBY_ORE_CLUSTER.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BUTTON.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_SMOOTH_STONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_COBBLESTONE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_COBBLESTONE_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_COBBLESTONE_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_COBBLESTONE_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_COBBLESTONE_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BRICKS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BRICKS_STAIRS.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BRICKS_SLAB.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BRICKS_WALL.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BRICKS_MOSSY.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BRICKS_CRACKED.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_BRICKS_CHISELED.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_IRON_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_GOLD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_COPPER_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_TIN_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_ZINC_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_DIAMOND_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_EMERALD_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_COAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_REDSTONE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_LAPIS_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_AQUAMARINE_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_OPAL_ORE.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_RUBY_ORE.get()),

                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_IRON_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_GOLD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_COPPER_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_TIN_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_ZINC_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_DIAMOND_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_EMERALD_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_COAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_REDSTONE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_LAPIS_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_AQUAMARINE_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_OPAL_ORE_CLUSTER.get()),
                Item.byBlock(ModBlocks.NIDAVELLIR_CRIMSON_STONE_RUBY_ORE_CLUSTER.get()),

                ModItems.CRIMSON_DIAMOND.get(),
                ModItems.NETHER_STEEL_INGOT.get(),
                ModItems.NETHER_STEEL_NUGGET.get(),
                ModItems.RAW_NETHER_STEEL.get(),
                ModItems.NETHER_STEEL_SWORD.get(),
                ModItems.NETHER_STEEL_PICKAXE.get(),
                ModItems.NETHER_STEEL_SHOVEL.get(),
                ModItems.NETHER_STEEL_AXE.get(),
                ModItems.NETHER_STEEL_HOE.get(),
                ModItems.NETHER_STEEL_PAXEL.get(),
                ModItems.NETHER_STEEL_HAMMER.get(),
                ModItems.NETHER_STEEL_HELMET.get(),
                ModItems.NETHER_STEEL_CHESTPLATE.get(),
                ModItems.NETHER_STEEL_LEGGINGS.get(),
                ModItems.NETHER_STEEL_BOOTS.get(),
                ModItems.NETHER_STEEL_HORSE_ARMOR.get(),

                Item.byBlock(ModBlocks.CRIMSON_STONE.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_STAIRS.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_SLAB.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_PRESSURE_PLATE.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_BUTTON.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_FENCE.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_FENCE_GATE.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_WALL.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_DOOR.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_TRAPDOOR.get()),
                Item.byBlock(ModBlocks.CRIMSON_COBBLESTONE.get()),
                Item.byBlock(ModBlocks.CRIMSON_COBBLESTONE_STAIRS.get()),
                Item.byBlock(ModBlocks.CRIMSON_COBBLESTONE_SLAB.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_BRICKS.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_BRICK_STAIRS.get()),
                Item.byBlock(ModBlocks.CRIMSON_STONE_BRICK_SLAB.get()),

                ModItems.AQUAMARINE.get(),
                ModItems.OPAL.get(),
                ModItems.RUBY.get(),

                ModItems.CRIMSON_APPLE.get(),
                ModItems.CRIMSON_TEAR.get(),

                Item.byBlock(ModBlocks.CRIMSON_DIAMOND_BLOCK.get()),
                Item.byBlock(ModBlocks.CRIMSON_DIAMOND_LAMP.get()),
                Item.byBlock(ModBlocks.NETHER_STEEL_BLOCK.get()),
                Item.byBlock(ModBlocks.RAW_NETHER_STEEL_BLOCK.get()),
                Item.byBlock(ModBlocks.NETHER_STEEL_ORE.get()),
                Item.byBlock(ModBlocks.DEEPSLATE_NETHER_STEEL_ORE.get())
        );

        this.tag(ModTags.CreativeTabs.ALFHEIMR).add(
                Item.byBlock(ModBlocks.ALFHEIMR_PORTAL_FRAME.get()),

                Item.byBlock(ModBlocks.ALFHEIMR_MAGIC_GRASS.get()),

                Item.byBlock(ModBlocks.DARK_BLOOM_FLOWER.get()),
                Item.byBlock(ModBlocks.DREAD_NIGHT_FLOWER.get()),
                Item.byBlock(ModBlocks.BLACK_LOTUS_FLOWER.get()),
                Item.byBlock(ModBlocks.NIGHT_ROSE_FLOWER.get()),
                Item.byBlock(ModBlocks.AQUA_ROSE_FLOWER.get()),
                Item.byBlock(ModBlocks.MOON_FLOWER.get()),
                Item.byBlock(ModBlocks.CATHERINE_FLOWER.get()),
                Item.byBlock(ModBlocks.TAINTED_ROSE_FLOWER.get()),
                Item.byBlock(ModBlocks.CINNAMON_ROSE_FLOWER.get()),
                Item.byBlock(ModBlocks.BUTTERFLY_FLOWER.get()),
                Item.byBlock(ModBlocks.GAIA_TULIP_FLOWER.get()),
                Item.byBlock(ModBlocks.BEARDED_IRIS_FLOWER.get()),
                Item.byBlock(ModBlocks.CORNFLOWER_FLOWER.get()),
                Item.byBlock(ModBlocks.MORNING_GLORY_FLOWER.get()),
                Item.byBlock(ModBlocks.GEORGIA_BLUE_FLOWER.get()),
                Item.byBlock(ModBlocks.BLUE_POPPY_FLOWER.get()),
                Item.byBlock(ModBlocks.TULIP_FLOWER.get()),
                Item.byBlock(ModBlocks.CARNATION_FLOWER.get()),
                Item.byBlock(ModBlocks.LADYS_MANTLE_FLOWER.get()),
                Item.byBlock(ModBlocks.GREEN_ROSE_FLOWER.get()),
                Item.byBlock(ModBlocks.CLEMATIS_FLOWER.get()),
                Item.byBlock(ModBlocks.BLUE_STAR_FLOWER.get()),
                Item.byBlock(ModBlocks.SALVIA_FLOWER.get()),
                Item.byBlock(ModBlocks.FALSE_INDIGO_FLOWER.get()),
                Item.byBlock(ModBlocks.WHITE_SAGE_FLOWER.get()),
                Item.byBlock(ModBlocks.SILVER_SCHEHERAZADE_FLOWER.get()),
                Item.byBlock(ModBlocks.SILVER_SPRING_FLOWER.get()),
                Item.byBlock(ModBlocks.SILVER_SHADOWS_FLOWER.get()),
                Item.byBlock(ModBlocks.GREEN_BALL_FLOWER.get()),
                Item.byBlock(ModBlocks.LIME_DAHLIA_FLOWER.get()),
                Item.byBlock(ModBlocks.HYDRANGEA_FLOWER.get()),
                Item.byBlock(ModBlocks.ZINNIA_FLOWER.get()),
                Item.byBlock(ModBlocks.BUTTERFLY_CANDY_FLOWER.get()),
                Item.byBlock(ModBlocks.CABARET_FLOWER.get()),
                Item.byBlock(ModBlocks.DIANTHUS_FLOWER.get()),
                Item.byBlock(ModBlocks.TITAN_CRANBERRY_VINCA_FLOWER.get()),
                Item.byBlock(ModBlocks.ORANGE_ZINNIA_FLOWER.get()),
                Item.byBlock(ModBlocks.BEGONIA_FLOWER.get()),
                Item.byBlock(ModBlocks.CROWN_IMPERIAL_FLOWER.get()),
                Item.byBlock(ModBlocks.ORIENTAL_POPPY_FLOWER.get()),
                Item.byBlock(ModBlocks.AZALEA_FLOWER.get()),
                Item.byBlock(ModBlocks.PINK_DELIGHT_FLOWER.get()),
                Item.byBlock(ModBlocks.CHRYSANTHEMUM_FLOWER.get()),
                Item.byBlock(ModBlocks.HIBISCUS_FLOWER.get()),
                Item.byBlock(ModBlocks.CARDINAL_FLOWER.get()),
                Item.byBlock(ModBlocks.GERBERA_FLOWER.get()),
                Item.byBlock(ModBlocks.RED_TULIP_FLOWER.get()),
                Item.byBlock(ModBlocks.FREESIA_FLOWER.get()),
                Item.byBlock(ModBlocks.GARDENIAS_FLOWER.get()),
                Item.byBlock(ModBlocks.STAR_JASMINE_FLOWER.get()),
                Item.byBlock(ModBlocks.WHITE_WARATAH_FLOWER.get()),
                Item.byBlock(ModBlocks.FLANNEL_FLOWER.get()),
                Item.byBlock(ModBlocks.BEARS_EARS_FLOWER.get()),
                Item.byBlock(ModBlocks.BIDENS_FLOWER.get()),
                Item.byBlock(ModBlocks.BLANKET_FLOWER.get()),
                Item.byBlock(ModBlocks.BULBINE_FLOWER.get()),
                Item.byBlock(ModBlocks.SILVER_BRUNIA_FLOWER.get()),
                Item.byBlock(ModBlocks.GRAY_ROSES_FLOWER.get()),
                Item.byBlock(ModBlocks.MOON_CARROT_FLOWER.get()),
                Item.byBlock(ModBlocks.SILVER_BABY_FLOWER.get()),
                Item.byBlock(ModBlocks.LAVENDER_FLOWER.get()),
                Item.byBlock(ModBlocks.BELLFLOWER_FLOWER.get()),
                Item.byBlock(ModBlocks.LILAC_FLOWER.get()),
                Item.byBlock(ModBlocks.SWEET_PEA_FLOWER.get()),

                ModItems.DURUM_WHEAT.get(),
                ModItems.DURUM_WHEAT_SEEDS.get(),
                ModItems.TOMATO.get(),
                ModItems.TOMATO_SEEDS.get(),
                ModItems.WILD_ONION.get(),
                ModItems.ONION_STAGE_1.get(),
                ModItems.ONION_STAGE_2.get(),
                ModItems.ONION_STAGE_3.get(),
                ModItems.ONION.get(),
                ModItems.DRAGON_FRUIT.get(),
                ModItems.DRAGON_FRUIT_SEEDS.get(),
                ModItems.CHILLI.get(),
                ModItems.CHILLI_SEEDS.get(),

                Item.byBlock(ModBlocks.POINT_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.TOP_POINT_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.POINT_MUSHROOM_STEM_BLOCK.get()),

                Item.byBlock(ModBlocks.WITCHES_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.TOP_WITCHES_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.WITCHES_MUSHROOM_STEM_BLOCK.get()),

                Item.byBlock(ModBlocks.ROYAL_BLUE_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.TOP_ROYAL_BLUE_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.ROYAL_BLUE_MUSHROOM_STEM_BLOCK.get()),
                Item.byBlock(ModBlocks.ROYAL_BLUE_MUSHROOM_GLOW_BLOCK.get()),

                Item.byBlock(ModBlocks.SHORT_TOP_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.TOP_SHORT_TOP_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.SHORT_TOP_MUSHROOM_STEM_BLOCK.get()),

                Item.byBlock(ModBlocks.SPECTRAL_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.TOP_SPECTRAL_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.SPECTRAL_MUSHROOM_STEM_BLOCK.get()),

                Item.byBlock(ModBlocks.SHADE_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.SHADE_MUSHROOM_VINE_BLOCK.get()),

                Item.byBlock(ModBlocks.CAP_MUSHROOM_BLOCK.get()),
                Item.byBlock(ModBlocks.CAP_MUSHROOM_VINE_BLOCK.get())
        );

        this.tag(ModTags.CreativeTabs.ATLANTIS).add(
                Item.byBlock(ModBlocks.ATLANTIS_PORTAL_FRAME.get()),

                Item.byBlock(ModBlocks.ATLANTAS_WATER_REMOVER_BLOCK.get()),
                ModItems.CLOWNFISH_BUCKET.get(),
                ModItems.TANG_FISH_BUCKET.get(),

                ModItems.SHARK_TOOTH.get(),

                ModItems.RAW_TUNA.get(),
                ModItems.COOKED_TUNA.get(),

                ModItems.CLOWNFISH.get(),
                ModItems.COOKED_CLOWNFISH.get(),
                ModItems.TANG_FISH.get(),
                ModItems.COOKED_TANG_FISH.get()
        );

        this.tag(ModTags.CreativeTabs.SKYOPIA).add(
                Item.byBlock(ModBlocks.SKYOPIA_PORTAL_FRAME.get())
        );
    }
}
